[package]
name = "passivate_notify"
version = "0.1.0"
edition = "2024"

[dependencies]
passivate_core = { path = "../passivate_core" }
passivate_delegation = { path = "../passivate_delegation" }

notify.workspace = true
camino.workspace = true
dunce.workspace = true
