[package]
name = "passivate_notify"
version = "0.1.0"
edition = "2024"

[dependencies]
passivate_delegation = { path = "../passivate_delegation" }
passivate_hyp_model = { path = "../passivate_hyp_model" }

notify.workspace = true
camino.workspace = true
dunce.workspace = true
