[workspace]
members = [
    "passivate_core",
    "passivate_app",
    "passivate_delegation"
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[profile.test]
panic = "abort"

[profile.bench]
panic = "abort"