unstable_features = true
edition = "2024"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
force_multiline_blocks = true
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
spaces_around_ranges = true
trailing_comma = "Never"
max_width = 180
use_field_init_shorthand = true
error_on_line_overflow = true
error_on_unformatted = true