[package]
name = "passivate_core"
version = "0.1.0"
edition = "2024"

[dependencies]
passivate_delegation = { path = "../passivate_delegation", features = ["testing"]}
faux = "0.1.13"
nextest-runner = { path = "F:/Projects/passivate-nextest/nextest-runner" }
nextest-filtering = { path = "F:/Projects/passivate-nextest/nextest-filtering" }
clap = "4.5.48"
futures = "0.3.31"
fs_extra = "1.3.0"
thiserror = "2.0.11"
mockall = "0.13.1"
enum-as-inner = "0.6.1"
duct = "0.13.7"
chrono = "0.4.40"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = { version = "1.0", features = [ "preserve_order" ] }
indexmap = { version = "2.8.0", features = [ "serde" ] }
cargo_metadata = "0.19.2"
epaint = "0.31"
png = "0.17.16"
bon = "3.6.5"
crossbeam-channel = "0.5.14"
dunce = "1.0.5"
camino = "1.2.0"
guppy = "0.17.21"

[dev-dependencies]
rstest = "0.25.0"
stdext = "0.3.3"
pretty_assertions = "1.4.1"
galvanic-assert = "0.8.7"
