[package]
name = "passivate_core"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
fs_extra = "1.3.0"
thiserror = "2.0.11"
mockall = "0.13.1"
enum-as-inner = "0.6.1"
os_pipe = "1.2.1"
chrono = "0.4.40"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = { version = "1.0", features = [ "preserve_order" ] }
indexmap = { version = "2.8.0", features = [ "serde" ] }
cargo_metadata = "0.19.2"

[dev-dependencies]
rstest = "0.25.0"
stdext = "0.3.3"
pretty_assertions = "1.4.1"
galvanic-assert = "0.8.7"