[package]
name = "passivate_hyp_names"
version = "0.1.0"
edition = "2024"

[dependencies]
stdext.workspace = true
thiserror.workspace = true

[dev-dependencies]
rstest.workspace = true
galvanic-assert.workspace = true