[package]
name = "passivate"
version = "0.1.0"
edition = "2021"

[dependencies]
passivate_core = { path = "../passivate_core" }

egui = "0.31"
eframe = { version = "0.31", default-features = false, features = [
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
] }
egui_dock = "0.16.0"
notify = "8.0.0"
futures = "0.3.31"