[package]
name = "passivate"
version = "0.1.0"
edition = "2021"

[dependencies]
passivate_core = { path = "../passivate_core" }

egui = { version = "0.31", features = [ ] }
egui_dock = "0.16.0"
notify = "8.0.0"
futures = "0.3.31"
tokio = { version = "1.42.0", features = [ "full" ] }

[dependencies.eframe]
version = "0.31"
default-features = false
features = [ "default_fonts", "wgpu", "accesskit", "wayland" ]

[dev-dependencies]
passivate_core = { path = "../passivate_core" }
mockall = "0.13.1"
libtest-mimic = "0.8.1"
egui_kittest = { version = "0.31.0", features = [ "wgpu", "snapshot" ] }
stdext = "0.3.3"

[[test]]
name = "passivate_tests"
harness = false