[package]
name = "passivate_hyp_model"
version = "0.1.0"
edition = "2024"

[dependencies]
passivate_hyp_names = { path = "../passivate_hyp_names" }

enum-as-inner.workspace = true
itertools.workspace = true
