name: Build Passivate
run-name: Build Passivate
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-update-default-toolchain
      - run: rustup toolchain uninstall stable
      - run: rustup toolchain install stable
      - run: rustup target add x86_64-unknown-linux-gnu
      - name: Test Core (Linux)
        working-directory: passivate/passivate_core
        run: cargo test
      - run: rustup target add x86_64-pc-windows-gnu
      - name: Build (Windows)
        working-directory: passivate
        run: cargo build --release --target x86_64-pc-windows-gnu